databases:
  - name: budget-app-db
    databaseName: budget_app_db_v42g
    user: budget_app_db_v42g_user

services:
  - type: web
    name: budget-application
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget-app-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
